SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 500
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 0.5
PLAYER_SPEED = 0.5
SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 5
PLAYER_SHOOT_COOLDOWN = 0.8